# permissions for end users to view prometheusexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheusexporter-viewer-role
rules:
- apiGroups:
  - metrics.turbonomic.io
  resources:
  - prometheusexporters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.turbonomic.io
  resources:
  - prometheusexporters/status
  verbs:
  - get
