apiVersion: metrics.turbonomic.io/v1alpha1
kind: PrometheusExporter
metadata:
  name: webdriver
spec:
  entities:
    - type: application
      hostedOnVM: true
      metrics:
        - type: responseTime
          queries:
            used: '1000*(navigation_timing_load_event_end_seconds{job="webdriver"}-navigation_timing_start_seconds{job="webdriver"})'
      attributes:
        ip:
          label: instance
          matches: \d{1,3}(?:\.\d{1,3}){3}(?::\d{1,5})??
          isIdentifier: true
        target:
          label: job
