apiVersion: metrics.turbonomic.io/v1alpha1
kind: PrometheusExporter
metadata:
  name: jmx-tomcat
spec:
  entities:
    - type: application
      hostedOnVM: true
      metrics:
        - type: cpu
          queries:
            used: 'java_lang_OperatingSystem_ProcessCpuLoad'
        - type: memory
          queries:
            used: 'java_lang_Memory_HeapMemoryUsage_used/1024'
            capacity: 'java_lang_Memory_HeapMemoryUsage_max/1024'
        - type: collectionTime
          queries:
            used: 'sum without (name) (delta(java_lang_GarbageCollector_CollectionTime)[10m])/600*100'
        - type: responseTime
          queries:
            used: 'rate(Catalina_GlobalRequestProcessor_processingTime{name=~".*http-.*"}[3m])'
      attributes:
        ip:
          label: instance
          matches: \d{1,3}(?:\.\d{1,3}){3}(?::\d{1,5})??
          isIdentifier: true
